// path constants live here, not in routes/, so features/ can import paths without importing routing logic
export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  HOME: '/home',
  EXPLORE: '/explore',
  PROFILE: '/profile/:username',
  MESSAGES: '/messages',
  NOTIFICATIONS: '/notifications',
  SAVED: '/saved',
  POST_DETAIL: '/post/:postId',
  SETTINGS: '/settings',
  SETTINGS_ACCOUNT: '/settings/account',
  SETTINGS_PRIVACY: '/settings/privacy',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  SETTINGS_APPEARANCE: '/settings/appearance',
  SETTINGS_SECURITY: '/settings/security',
  NOT_FOUND: '*',
  MESSAGES: '/messages',
  MESSAGE_THREAD: '/messages/:conversationId',
};